spring:
  profiles:
    include: aws

server:
  port: 4000

servlet:
  multipart:
    max-file-size: 100MB
    max-request-size: 110MB

secret-key: "123123j124y"

file:
  path: /Users/kyunggwanpark/Documents/
  url: http://localhost:4000/file/
